<?php

return CMap::mergeArray(
	require(dirname(__FILE__).'/main.php'),
	array(
		'import'=>array(
			'application.tests.components.*',
			'application.tests.helpers.*',
		),
		'components'=>array(
			'fixture'=>array(
				'class'=>'system.test.CDbFixtureManager',
				'basePath'=>dirname(__FILE__).'/../tests/fixtures',
			),
			'request'=>array(
				'class'=>'TestHttpRequest',
				'hostInfo'=>'http://localhost',
				'baseUrl'=>'/',
				'scriptUrl'=>'/index-test.php',
			),
			'assetManager'=>array(
				'basePath'=>dirname(__FILE__).'/../../assets',
				'baseUrl'=>'/assets',
			),
            'queue'=>array(
                'driver'=>'sync',
            ),
		),
	)
);
